# Regression Exercise 

California Housing Data

 It has been obtained from the LIACC repository. The original page where the data set can be found is: http://www.liaad.up.pt/~ltorgo/Regression/DataSets.html.
 

The Features:
 
* housingMedianAge: continuous. 
* totalRooms: continuous. 
* totalBedrooms: continuous. 
* population: continuous. 
* households: continuous. 
* medianIncome: continuous. 
* medianHouseValue: continuous. 

## The Data

In [5]:
import pandas as pd

In [6]:
housing_price = pd.read_csv('cal_housing_clean.csv')

In [7]:
housing_price.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  medianHouseValue  
0        8.3252          452600.0  
1        8.3014          358500.0  
2        7.2574          352100.0  
3        5.6431          341300.0  
4        3.8462          342200.0

In [8]:
housing_price.describe().transpose()

count           mean            std         min  \
housingMedianAge  20640.0      28.639486      12.585558      1.0000   
totalRooms        20640.0    2635.763081    2181.615252      2.0000   
totalBedrooms     20640.0     537.898014     421.247906      1.0000   
population        20640.0    1425.476744    1132.462122      3.0000   
households        20640.0     499.539680     382.329753      1.0000   
medianIncome      20640.0       3.870671       1.899822      0.4999   
medianHouseValue  20640.0  206855.816909  115395.615874  14999.0000   

                          25%          50%           75%          max  
housingMedianAge      18.0000      29.0000      37.00000      52.0000  
totalRooms          1447.7500    2127.0000    3148.00000   39320.0000  
totalBedrooms        295.0000     435.0000     647.00000    6445.0000  
population           787.0000    1166.0000    1725.00000   35682.0000  
households           280.0000     409.0000     605.00000    6082.0000  
medianIncome           2.5634       3.5348       4.74325      15.0001  
medianHouseValue  119600.0000  179700.0000  264725.00000  500001.0000

In [9]:
x_data = housing_price.drop('medianHouseValue',axis=1)

In [10]:
labels = housing_price['medianHouseValue']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x_data,labels,test_size=0.30, random_state=101)

In [13]:
from sklearn.preprocessing import MinMaxScaler 

In [14]:
scaler_model = MinMaxScaler()

In [15]:
scaler_model.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [16]:
scaled_X_train = scaler_model.transform(X_train)
print(scaled_X_train)

[[0.35294118 0.06968818 0.11716325 0.04876939 0.11544154 0.14250838]
 [0.60784314 0.01124167 0.01567349 0.00836747 0.01414241 0.04502697]
 [0.66666667 0.02523017 0.03134699 0.02097119 0.03025818 0.21286603]
 ...
 [0.09803922 0.08962816 0.08659218 0.0481392  0.08057885 0.38940153]
 [0.68627451 0.02110992 0.03258845 0.0189756  0.03453379 0.19181804]
 [0.43137255 0.08538074 0.11235258 0.0650842  0.10689031 0.14979104]]


In [17]:
scaled_X_test = scaler_model.transform(X_test)
print(scaled_X_test)

[[0.68627451 0.0462638  0.04515829 0.02587263 0.04884065 0.35313306]
 [0.70588235 0.02741747 0.02079454 0.01270875 0.02318698 0.77018248]
 [0.90196078 0.03232616 0.04081316 0.04166229 0.04259168 0.13362574]
 ...
 [0.1372549  0.02617122 0.03103662 0.02111123 0.0292715  0.15996331]
 [0.76470588 0.01144514 0.01675978 0.01431922 0.01578688 0.05805437]
 [0.58823529 0.14708276 0.21384233 0.10398067 0.21558954 0.19096288]]


In [18]:
scaled_X_train_dataframe = pd.DataFrame(data=scaled_X_train,columns= ['housingMedianAge','totalRooms','totalBedrooms','population'
,'households', 'medianIncome'])
scaled_X_train_dataframe.head(5)

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0          0.352941    0.069688       0.117163    0.048769    0.115442   
1          0.607843    0.011242       0.015673    0.008367    0.014142   
2          0.666667    0.025230       0.031347    0.020971    0.030258   
3          0.666667    0.032530       0.033830    0.024752    0.030094   
4          0.294118    0.031919       0.035692    0.019466    0.034863   

   medianIncome  
0      0.142508  
1      0.045027  
2      0.212866  
3      0.298651  
4      0.272631

In [19]:
scaled_X_test_dataframe = pd.DataFrame(data=scaled_X_test,columns= ['housingMedianAge','totalRooms','totalBedrooms','population'
,'households', 'medianIncome'])
scaled_X_test_dataframe.head(5)

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0          0.686275    0.046264       0.045158    0.025873    0.048841   
1          0.705882    0.027417       0.020795    0.012709    0.023187   
2          0.901961    0.032326       0.040813    0.041662    0.042592   
3          0.313725    0.043212       0.046089    0.032840    0.048018   
4          0.411765    0.088433       0.069367    0.043728    0.072192   

   medianIncome  
0      0.353133  
1      0.770182  
2      0.133626  
3      0.263576  
4      0.660046

### Create Feature Columns


In [20]:
housing_price.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [22]:
import tensorflow as tf 

ModuleNotFoundError: No module named 'tensorflow'

In [23]:
housing_Median_Age = tf.feature_column.numeric_column('housingMedianAge')
total_Rooms = tf.feature_column.numeric_column('totalRooms')
total_Bedrooms = tf.feature_column.numeric_column('totalBedrooms')
population_ = tf.feature_column.numeric_column('population')
thouseholds_ = tf.feature_column.numeric_column('households')
median_Income = tf.feature_column.numeric_column('medianIncome')

NameError: name 'tf' is not defined

In [24]:
feat_cols = [housing_Median_Age ,total_Rooms,total_Bedrooms ,population_ ,thouseholds_,median_Income]

NameError: name 'housing_Median_Age' is not defined

In [25]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=10,num_epochs=1000,shuffle=True)

NameError: name 'tf' is not defined

In [26]:
model = tf.estimator.DNNRegressor(hidden_units=[6, 6, 6],feature_columns=feat_cols)

NameError: name 'tf' is not defined

##### ** Train the model for ~1,000 steps. (Later come back to this and train it for more and check for improvement) **

In [27]:
model.train(input_fn=input_func,steps=20000)

NameError: name 'model' is not defined

** Create a prediction input function and then use the .predict method off your estimator model to create a list or predictions on your test data. **

In [28]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(
      x=X_test,
      batch_size=10,
      num_epochs=1,
      shuffle=False)

NameError: name 'tf' is not defined

In [29]:
predictions = model.predict(pred_input_func)

NameError: name 'model' is not defined

In [30]:
list(predictions)

NameError: name 'predictions' is not defined

In [31]:
y_predicted = []# np.array([])
for x in model.predict(pred_input_func):
    y_predicted.append(x['predictions'])

NameError: name 'model' is not defined

In [32]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [33]:
rms = sqrt(mean_squared_error(y_test, y_predicted))
print(rms)

ValueError: Found input variables with inconsistent numbers of samples: [6192, 0]